- job:
    name: grenade-postgresql
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-postgresql/run.yaml
    post-run: playbooks/legacy/grenade-postgresql/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
    irrelevant-files: &grenade-irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$

- job:
    name: grenade-dsvm-neutron-forward
    # Old name: grenade-dsvm-neutron-forward
    parent: legacy-dsvm-base
    # This is py3 version for ussuri onwards rest all branch needs to be py2
    # version which is present in openstack-zuul-jobs.
    # We need to take care of this branch variant and python version while
    # migrating these jobs to zuulv3.
    branches: ^(?!(stable/(ocata|pike|queens|rocky|stein|train))).*$
    run: playbooks/legacy/grenade-dsvm-neutron-forward/run.yaml
    post-run: playbooks/legacy/grenade-dsvm-neutron-forward/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
      - openstack/neutron

- job:
    name: grenade-py3
    parent: legacy-dsvm-base
    run: playbooks/legacy/grenade-py3/run.yaml
    post-run: playbooks/legacy/grenade-py3/post.yaml
    timeout: 10800
    required-projects:
      - openstack/grenade
      - openstack/devstack-gate
    irrelevant-files: *grenade-irrelevant-files

- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - neutron-grenade:
            irrelevant-files: *grenade-irrelevant-files
        - grenade-heat:
            voting: false
            irrelevant-files: *grenade-irrelevant-files
        - grenade-py3
        - neutron-grenade-multinode:
            irrelevant-files: *grenade-irrelevant-files
        - ironic-grenade-dsvm:
            voting: false
            irrelevant-files: *grenade-irrelevant-files
    gate:
      jobs:
        - grenade-py3
        - neutron-grenade:
            irrelevant-files: *grenade-irrelevant-files
        - neutron-grenade-multinode:
            irrelevant-files: *grenade-irrelevant-files
    experimental:
      jobs:
        - grenade-postgresql
        - grenade-dsvm-neutron-forward:
            irrelevant-files: *grenade-irrelevant-files
        - trove-grenade:
            irrelevant-files: *grenade-irrelevant-files

